### ISSUE TITLE
不能二维码签到

### ISSUE THREAD

**Issue by chenlvtang** [Huangyan0804/AutoCheckin#3]
好像无法实现二维码签到

**Comment by chenlvtang** [comment]
> 好像无法实现二维码签到

![image](https://user-images.githubusercontent.com/56435336/111606815-9f664280-8812-11eb-80ea-f30d1f8cf712.png)

**Comment by SaarChaffee** [comment]
二维码要手动在265行加上你二维码的enc（也就是二维码的验证码）才行
![image](https://user-images.githubusercontent.com/53519746/112096912-17998300-8bda-11eb-95fb-9dc465277a47.png)

**Comment by chenlvtang** [comment]
这个enc是要自己手动二维码解码后才能查看到吗，那这样我完全可以自己手动签到吧，而且现在的二维码签到都是10s一换，根本摸不到🐟。作者大大如果有什么办法完善一下就好了。RESPECT！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月23日(星期二) 中午1:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Huangyan0804/AutoCheckin] 不能二维码签到 (#3)





 
二维码要手动在265行加上你二维码的enc（也就是二维码的验证码）才行

**Comment by SaarChaffee** [comment]
> 这个enc是要自己手动二维码解码后才能查看到吗，那这样我完全可以自己手动签到吧，而且现在的二维码签到都是10s一换，根本摸不到🐟。作者大大如果有什么办法完善一下就好了。RESPECT！！
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年3月23日(星期二) 中午1:17 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [Huangyan0804/AutoCheckin] 不能二维码签到 (#3) 二维码要手动在265行加上你二维码的enc（也就是二维码的验证码）才行 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

其实同一个签到的enc是一样的（如果有人跟你上同一节课让他拍个二维码给你然后解码就行，不过都这样了为什么不让他多开学习通帮你签呢_(:з」∠)_
