### ISSUE TITLE
二维码签到好像用不了

### ISSUE THREAD

**Issue by LittleGauss** [Huangyan0804/AutoCheckin#4]
![屏幕截图 2021-12-25 172022](https://user-images.githubusercontent.com/92156835/147382004-7d7c63c4-ca83-4474-bd26-ae4ce3f55956.png)
他会直接跳过，是我操作问题吗

**Comment by Huangyan0804** [comment]
学习通更新了二维码签到方式，详情查看 #3

**Comment by LittleGauss** [comment]
抱歉大佬 有点小白了 刚接触爬虫 
![屏幕截图 2021-12-25 181638](https://user-images.githubusercontent.com/92156835/147382880-14cf54c4-0433-428d-9d41-f84c8b69421c.png)
是这样加 还是说另外加一行"&enc=4F10BD8D30593C175870D11197608772"
